spring.application.name=staminaBackend

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://db.nmvykilfvxmjlmqhywsz.supabase.co:6543/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=D1qSIDzfjLTYdNnJ
spring.datasource.url=jdbc:postgresql://dpg-d7g2olosfn5c739slgj0-a:5432/staminadb
spring.datasource.username=staminadb_user
spring.datasource.password=eyu1FUNzCyLEwdXj6W0hSerXqKpQv5As
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.username=postgres
#spring.datasource.password=root